name: mq_quran_client
description: MyQuran Quran Client
version: 0.1.0+1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  meta:
  json_annotation:
  equatable:
  mq_remote_client:
  mq_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  build_runner:
  json_serializable:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/quran_pages/

  fonts:
    - family: uthmanic_hafs
      fonts:
        - asset: assets/fonts/uthmanic_hafs/UthmanicHafs1Ver18.woff2
    - family: surah_names
      fonts:
        - asset: assets/fonts/surah_names/sura_names.woff2

flutter_gen:
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
      class_name: QuranAssets
  fonts:
    outputs:
      class_name: QuranFontFamily
  output: lib/generated/
  line_length: 120

  integrations:
    flutter_svg: true
