name: mq_auth_repository
description: MyQuran Auth Repository
version: 0.1.0+1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  meta:
  json_annotation:
  firebase_auth:
  google_sign_in:
  sign_in_with_apple:

  mq_crashlytics:
  mq_storage:
  mq_remote_client:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  build_runner:
  json_serializable:
