name: mq_home_repository
description: MQ Home Repository Package
version: 0.1.0+1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  json_annotation:

  mq_crashlytics:
  mq_remote_client:
  mq_remote_config:
  mq_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:
  build_runner:
  json_serializable:
