name: mq_hatim_repository
description: Mq hatim repository package
version: 0.1.0+1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  json_annotation:
  web_socket_channel:
  web_socket_client:
  mq_crashlytics:
  mq_remote_client:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mocktail:
  json_serializable:
