name: CD IOS (Release Build)

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy_ios:
    runs-on: macos-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5

      - name: Install Certificate and Profile
        env:
          P12_BASE64: ${{ secrets.IOS_P12_BASE64 }}
          P12_PASSWORD: ${{ secrets.IOS_P12_PASSWORD }}
          PROFILE_BASE64: ${{ secrets.IOS_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: "temporary_password"
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$P12_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$PROFILE_BASE64" | base64 --decode -o $PP_PATH

          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: "Set up Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.6"
          channel: stable

      - run: flutter doctor -v

      - name: "Install Global Tools (flutterfire_cli & melos)"
        run: |
          dart pub global activate flutterfire_cli
          dart pub global activate melos

      - name: "Melos Bootstrap"
        run: melos bootstrap

      - name: Build IPA
        run: |
          cd app
          flutter build ipa --release \
          --export-options-plist=ios/Runner/ExportOptions.plist \
          -- \
          CODE_SIGN_STYLE=Manual \
          PROVISIONING_PROFILE_SPECIFIER="MyQuranGuthabActionCD" \
          DEVELOPMENT_TEAM="L8HXY9BDGG" \
          CODE_SIGN_IDENTITY="Apple Distribution"

      - name: Show Generated files
        run: |
          ls app/build/ios/ipa

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Runner.ipa
          path: app/build/ios/ipa/Runner.ipa

      - name: Upload to TestFlight
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: "app/build/ios/ipa/*.ipa"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
